# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
Location.delete_all
Organization.delete_all
GroupOrganization.delete_all
Country.delete_all

country = Country.create!(name: 'Polska', country_code: "PL")

group = GroupOrganization.create!(name: "PLGroupOrganization1", organization_code: "PLGroupOrg1", country_id: country.id)
org1 = Organization.create!(name: 'PLOrganization1', org_type: 'Service', pricing_policy: 'Flexible', group_organization_id: group.id)
Location.create!(name: 'address1', address: 'address', organization_id: org1.id)
Location.create!(name: 'address2', address: 'address', organization_id: org1.id)
org2 = Organization.create!(name: 'PLOrganization2', org_type: 'Service', pricing_policy: 'Fixed', group_organization_id: group.id)
Location.create!(name: 'address1', address: 'address', organization_id: org2.id)
Location.create!(name: 'address2', address: 'address', organization_id: org2.id)
org3 = Organization.create!(name: 'PLOrganization3', org_type: 'Service', pricing_policy: 'Prestige', group_organization_id: group.id)
Location.create!(name: 'address1', address: 'address', organization_id: org3.id)
Location.create!(name: 'address2', address: 'address', organization_id: org3.id)
org4 = Organization.create!(name: 'PLOrganization4', org_type: 'Service', pricing_policy: 'Flexible', group_organization_id: group.id, organization_id: org1.id)
Location.create!(name: 'address1', address: 'address', organization_id: org4.id)
Location.create!(name: 'address2', address: 'address', organization_id: org4.id)
org5 = Organization.create!(name: 'PLOrganization5', org_type: 'Service', pricing_policy: 'Fixed', group_organization_id: group.id, organization_id: org1.id)
Location.create!(name: 'address1', address: 'address', organization_id: org5.id)
Location.create!(name: 'address2', address: 'address', organization_id: org5.id)
org6 = Organization.create!(name: 'PLOrganization5', org_type: 'Service', pricing_policy: 'Prestige', group_organization_id: group.id, organization_id: org1.id)
Location.create!(name: 'address1', address: 'address', organization_id: org6.id)
Location.create!(name: 'address2', address: 'address', organization_id: org6.id)


group = GroupOrganization.create!(name: "PLOrganization2", organization_code: "PLOrg2", country_id: country.id)
org1 = Organization.create!(name: 'PLOrganization1', org_type: 'Service', pricing_policy: 'Flexible', group_organization_id: group.id)
Location.create!(name: 'address1', address: 'address', organization_id: org1.id)
Location.create!(name: 'address2', address: 'address', organization_id: org1.id)
org2 = Organization.create!(name: 'PLOrganization2', org_type: 'Service', pricing_policy: 'Fixed', group_organization_id: group.id)
Location.create!(name: 'address1', address: 'address', organization_id: org2.id)
Location.create!(name: 'address2', address: 'address', organization_id: org2.id)
org3 = Organization.create!(name: 'PLOrganization3', org_type: 'Service', pricing_policy: 'Prestige', group_organization_id: group.id)
Location.create!(name: 'address1', address: 'address', organization_id: org3.id)
Location.create!(name: 'address2', address: 'address', organization_id: org3.id)
org4 = Organization.create!(name: 'PLOrganization4', org_type: 'Service', pricing_policy: 'Flexible', group_organization_id: group.id, organization_id: org1.id)
Location.create!(name: 'address1', address: 'address', organization_id: org4.id)
Location.create!(name: 'address2', address: 'address', organization_id: org4.id)
org5 = Organization.create!(name: 'PLOrganization5', org_type: 'Service', pricing_policy: 'Fixed', group_organization_id: group.id, organization_id: org1.id)
Location.create!(name: 'address1', address: 'address', organization_id: org5.id)
Location.create!(name: 'address2', address: 'address', organization_id: org5.id)
org6 = Organization.create!(name: 'PLOrganization5', org_type: 'Service', pricing_policy: 'Prestige', group_organization_id: group.id, organization_id: org1.id)
Location.create!(name: 'address1', address: 'address', organization_id: org6.id)
Location.create!(name: 'address2', address: 'address', organization_id: org6.id)


country = Country.create!(name: 'Singapur', country_code: "SG")
group = GroupOrganization.create!(name: "SGGroupOrganization1", organization_code: "SGGroupOrg1", country_id: country.id)
org1 = Organization.create!(name: 'SGOrganization1', org_type: 'Service', pricing_policy: 'Flexible', group_organization_id: group.id)
Location.create!(name: 'address1', address: 'address', organization_id: org1.id)
Location.create!(name: 'address2', address: 'address', organization_id: org1.id)
org2 = Organization.create!(name: 'SGOrganization2', org_type: 'Service', pricing_policy: 'Fixed', group_organization_id: group.id)
Location.create!(name: 'address1', address: 'address', organization_id: org2.id)
Location.create!(name: 'address2', address: 'address', organization_id: org2.id)
org3 = Organization.create!(name: 'SGOrganization3', org_type: 'Service', pricing_policy: 'Prestige', group_organization_id: group.id)
Location.create!(name: 'address1', address: 'address', organization_id: org3.id)
Location.create!(name: 'address2', address: 'address', organization_id: org3.id)
org4 = Organization.create!(name: 'SGOrganization4', org_type: 'Service', pricing_policy: 'Flexible', group_organization_id: group.id, organization_id: org1.id)
Location.create!(name: 'address1', address: 'address', organization_id: org4.id)
Location.create!(name: 'address2', address: 'address', organization_id: org4.id)
org5 = Organization.create!(name: 'SGOrganization5', org_type: 'Service', pricing_policy: 'Fixed', group_organization_id: group.id, organization_id: org1.id)
Location.create!(name: 'address1', address: 'address', organization_id: org5.id)
Location.create!(name: 'address2', address: 'address', organization_id: org5.id)
org6 = Organization.create!(name: 'PLOrganization5', org_type: 'Service', pricing_policy: 'Prestige', group_organization_id: group.id, organization_id: org1.id)
Location.create!(name: 'address1', address: 'address', organization_id: org6.id)
Location.create!(name: 'address2', address: 'address', organization_id: org6.id)


group = GroupOrganization.create!(name: "SGOrganization2", organization_code: "SGOrg2", country_id: country.id)
org1 = Organization.create!(name: 'SGOrganization1', org_type: 'Service', pricing_policy: 'Flexible', group_organization_id: group.id)
Location.create!(name: 'address1', address: 'address', organization_id: org1.id)
Location.create!(name: 'address2', address: 'address', organization_id: org1.id)
org2 = Organization.create!(name: 'SGOrganization2', org_type: 'Service', pricing_policy: 'Fixed', group_organization_id: group.id)
Location.create!(name: 'address1', address: 'address', organization_id: org2.id)
Location.create!(name: 'address2', address: 'address', organization_id: org2.id)
org3 = Organization.create!(name: 'SGOrganization3', org_type: 'Service', pricing_policy: 'Prestige', group_organization_id: group.id)
Location.create!(name: 'address1', address: 'address', organization_id: org3.id)
Location.create!(name: 'address2', address: 'address', organization_id: org3.id)
org4 = Organization.create!(name: 'SGOrganization4', org_type: 'Service', pricing_policy: 'Flexible', group_organization_id: group.id, organization_id: org1.id)
Location.create!(name: 'address1', address: 'address', organization_id: org4.id)
Location.create!(name: 'address2', address: 'address', organization_id: org4.id)
org5 = Organization.create!(name: 'SGOrganization5', org_type: 'Service', pricing_policy: 'Fixed', group_organization_id: group.id, organization_id: org1.id)
Location.create!(name: 'address1', address: 'address', organization_id: org5.id)
Location.create!(name: 'address2', address: 'address', organization_id: org5.id)
org6 = Organization.create!(name: 'PLOrganization5', org_type: 'Service', pricing_policy: 'Prestige', group_organization_id: group.id, organization_id: org1.id)
Location.create!(name: 'address1', address: 'address', organization_id: org6.id)
Location.create!(name: 'address2', address: 'address', organization_id: org6.id)


country = Country.create!(name: 'Niemcy', country_code: "DE")
group = GroupOrganization.create!(name: "DEGroupOrganization1", organization_code: "DEGroupOrg1", country_id: country.id)
org1 = Organization.create!(name: 'DEOrganization1', org_type: 'Service', pricing_policy: 'Flexible', group_organization_id: group.id)
Location.create!(name: 'address1', address: 'address', organization_id: org1.id)
Location.create!(name: 'address2', address: 'address', organization_id: org1.id)
org2 = Organization.create!(name: 'DEOrganization2', org_type: 'Service', pricing_policy: 'Fixed', group_organization_id: group.id)
Location.create!(name: 'address1', address: 'address', organization_id: org2.id)
Location.create!(name: 'address2', address: 'address', organization_id: org2.id)
org3 = Organization.create!(name: 'DEOrganization3', org_type: 'Service', pricing_policy: 'Prestige', group_organization_id: group.id)
Location.create!(name: 'address1', address: 'address', organization_id: org3.id)
Location.create!(name: 'address2', address: 'address', organization_id: org3.id)
org4 = Organization.create!(name: 'DEOrganization4', org_type: 'Service', pricing_policy: 'Flexible', group_organization_id: group.id, organization_id: org1.id)
Location.create!(name: 'address1', address: 'address', organization_id: org4.id)
Location.create!(name: 'address2', address: 'address', organization_id: org4.id)
org5 = Organization.create!(name: 'DEOrganization5', org_type: 'Service', pricing_policy: 'Fixed', group_organization_id: group.id, organization_id: org1.id)
Location.create!(name: 'address1', address: 'address', organization_id: org5.id)
Location.create!(name: 'address2', address: 'address', organization_id: org5.id)
org6 = Organization.create!(name: 'PLOrganization5', org_type: 'Service', pricing_policy: 'Prestige', group_organization_id: group.id, organization_id: org1.id)
Location.create!(name: 'address1', address: 'address', organization_id: org6.id)
Location.create!(name: 'address2', address: 'address', organization_id: org6.id)


group = GroupOrganization.create!(name: "DEOrganization2", organization_code: "DEOrg2", country_id: country.id)
org1 = Organization.create!(name: 'DEOrganization1', org_type: 'Service', pricing_policy: 'Flexible', group_organization_id: group.id)
Location.create!(name: 'address1', address: 'address', organization_id: org1.id)
Location.create!(name: 'address2', address: 'address', organization_id: org1.id)
org2 = Organization.create!(name: 'DEOrganization2', org_type: 'Service', pricing_policy: 'Fixed', group_organization_id: group.id)
Location.create!(name: 'address1', address: 'address', organization_id: org2.id)
Location.create!(name: 'address2', address: 'address', organization_id: org2.id)
org3 = Organization.create!(name: 'DEOrganization3', org_type: 'Service', pricing_policy: 'Prestige', group_organization_id: group.id)
Location.create!(name: 'address1', address: 'address', organization_id: org3.id)
Location.create!(name: 'address2', address: 'address', organization_id: org3.id)
org4 = Organization.create!(name: 'DEOrganization4', org_type: 'Service', pricing_policy: 'Flexible', group_organization_id: group.id, organization_id: org1.id)
Location.create!(name: 'address1', address: 'address', organization_id: org4.id)
Location.create!(name: 'address2', address: 'address', organization_id: org4.id)
org5 = Organization.create!(name: 'DEOrganization5', org_type: 'Service', pricing_policy: 'Fixed', group_organization_id: group.id, organization_id: org1.id)
Location.create!(name: 'address1', address: 'address', organization_id: org5.id)
Location.create!(name: 'address2', address: 'address', organization_id: org5.id)
org6 = Organization.create!(name: 'PLOrganization5', org_type: 'Service', pricing_policy: 'Prestige', group_organization_id: group.id, organization_id: org1.id)
Location.create!(name: 'address1', address: 'address', organization_id: org6.id)
Location.create!(name: 'address2', address: 'address', organization_id: org6.id)
